# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:


#asdfsadfg
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'lbf-sharepoint/poc-devops'

- task: Gulp@1
  inputs:
    gulpFile: 'gulpfile.js'
    targets: 'bundle'
    arguments: '--ship'
    workingDirectory: 'lbf-sharepoint/poc-devops'
    enableCodeCoverage: false




- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'SPFx sppkg'
    pathtoPublish: '$(Build.SourceDirectory)/sharepoint/solution/poc.sppkg'
  displayName: 'Publish build SPFx artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.SourceDirectory)/devops/release'
    artifactName: 'Office 365 CLI scripts'
  displayName: 'Publish build Office 365 CLI artifacts'