# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install gulp -g
  displayName: 'npm install'

- script: |
    gulp clean
    gulp bundle --ship
    gulp package-solution --ship
  displayName: 'Build and panckage SPFx solution'

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'SPFx sppkg'
    pathtoPublish: '$(Build.SourceDirectory)/sharepoint/solution/poc.sppkg'
  displayName: 'Publish build SPFx artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.SourceDirectory)/devops/release'
    artifactName: 'Office 365 CLI scripts'
  displayName: 'Publish build Office 365 CLI artifacts'