declare const styles: {
    ccPanelHeader: string;
    ccPanelMain: string;
    ccitemCell: string;
    ccitemCellContent: string;
    'ms-Grid': string;
    ccitemCellLBFavourite: string;
    msFabric: string;
    'is-focusVisible': string;
    ccRow: string;
    ccTopBar: string;
    ccitemContent: string;
    ccInitials: string;
    ccitemName: string;
    ccitemDesc: string;
    ccStatus: string;
    ccButton: string;
    ccTopBarButton: string;
    ccDialogButton: string;
    iconsContainer: string;
    iconPrimaryColor: string;
    iconWarningColor: string;
    addToFavouritesBtn: string;
    spinnerContainer: string;
};
export default styles;
